name: cse489_lab_mid
description: "A new Flutter project."
publish_to: "none"
version: 0.1.1

environment:
    sdk: ^3.9.2

dependencies:
    flutter:
        sdk: flutter
    google_maps_flutter: ^2.14.0
    http: ^1.2.2
    http_parser: ^4.0.0
    image_picker: ^1.1.2
    image: ^4.2.0
    geolocator: ^14.0.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true
